### PR TITLE
[WIP] Make binpath configurable via g:JuliaFormatter_julia_path

### PR DESCRIPTION
**Pull request by lassepe**
This is a stab at #43 . This is just a quick draft to discuss the idea.

I think one would have to also update `lua/juliaformatter.lua` since that has the Julia binary hard-coded at various places but I have no idea how/where this code is used (formatting, at least, already works with this PR). Also, before this gets merged, I would have to add a section to the README.

### CODE REVIEW

**Comment by kdheepak** [comment]
Oops I misclicked and hit ready for review! 😅 

I agree with your changes! Thanks for taking a first stab at it. I’ll look into this this weekend.

**Comment by kdheepak** [comment]
> I think one would have to also update lua/juliaformatter.lua

The lua file is not being used for the actual functionality. It is stuff I was experimenting that is neovim specific. So that doesn't need to be updated for now.

**Comment by lassepe** [comment]
Now that  [LanguageServer.jl](https://github.com/julia-vscode/LanguageServer.jl/pull/972) support JuliaFormatter.jl directly, I am actually not using this plugin anymore since formatting can be done directly through [coc-julia](https://github.com/fannheyward/coc-julia). I am thus closing this PR.

**Comment by kdheepak** [comment]
This feature was added in https://github.com/kdheepak/JuliaFormatter.vim/commit/65d4e2625da00becf7b08c34683933320de0d306

**Pull request closed without merging**
