### PR TITLE
Fixed instantiation when not possible

### PR DESCRIPTION
**Pull request by 00sapo**

### CODE REVIEW

**Comment by kdheepak** [comment]
Thanks for making a PR! Can you explain 

1. why does pkg instantiate fail in the first place?
2. why does the try except have to be after the using? Wouldn’t that fail if the packages weren’t instantiated?

**Comment by kdheepak** [comment]
Can you move the try catch to the beginning?

**Comment by 00sapo** [comment]
>     1. why does pkg instantiate fail in the first place?
Here is the stack-trace for julia 1.3.1

```julia
ERROR: LoadError: MethodError: no method matching joinpath(::Nothing)
Closest candidates are:
  joinpath(!Matched::String, !Matched::String) at path.jl:265
  joinpath(!Matched::AbstractString) at path.jl:247
  joinpath(!Matched::AbstractString, !Matched::AbstractString) at path.jl:274
  ...
Stacktrace:
 [1] stat(::Nothing) at ./stat.jl:109
 [2] isdir(::Nothing) at ./stat.jl:311
 [3] is_instantiated(::Pkg.Types.Context) at /buildworker/worker/package_linux64/build/usr/share/julia
/stdlib/v1.3/Pkg/src/Operations.jl:83
 [4] #instantiate#114(::Nothing, ::Bool, ::Bool, ::Pkg.BinaryPlatforms.Linux, ::Base.Iterators.Pairs{U
nion{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.instantiate), ::Pkg.Types.Context) at
 /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:738
 [5] instantiate(::Pkg.Types.Context) at /buildworker/worker/package_linux64/build/usr/share/julia/std
lib/v1.3/Pkg/src/API.jl:720
 [6] #instantiate#113 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src
/API.jl:716 [inlined]
 [7] instantiate() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/AP
I.jl:716
 [8] top-level scope at /home/sapo/.local/share/nvim/plugged/JuliaFormatter.vim/scripts/server.jl:2
 [9] include at ./boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at ./loading.jl:1105
 [11] include(::Module, ::String) at ./Base.jl:31
 [12] exec_options(::Base.JLOptions) at ./client.jl:287
 [13] _start() at ./client.jl:460
in expression starting at /home/sapo/.local/share/nvim/plugged/JuliaFormatter.vim/scripts/server.jl:2

```

>     2. why does the try except have to be after the using? Wouldn’t that fail if the packages weren’t instantiated?

Yes, I have now fixed it, and also added hint in the log file for installing dependencies by hand


> Can you move the try catch to the beginning?

Did it! But after having defined the `log` function (for the above point)

**Review by kdheepak — APPROVED** [review]

**Comment by kdheepak** [comment]
Thanks for the PR. I’m curious why you are using Julia 1.3.x and if you can’t upgrade to a more recent version?

**Comment by 00sapo** [comment]
Thank you so much! The reason why I'm still using Julia 1.3.1 is Cxx, that supports Julia 1.1 to 1.3. I hope this will be fixed soon

**Comment by kdheepak** [comment]
Ah, makes sense!

**Comment by kdheepak** [comment]
Currently the printing is too long and is causing vim to require pressing enter after the `echo` (depending on the width of vim). I made the following change:

https://github.com/kdheepak/JuliaFormatter.vim/commit/ba272dca2530eab3ab926f2d88f3fffab92d8b4c#diff-3663da2ef160978d9873524afcda5108444be143d6408a3c187334021de12019R165

You can now use `:JuliaFormatterEchoCmd` to get the command that is being executed.

**Pull request merged**
